name: "构建发布 Docker"

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
  workflow_dispatch:

env:
  PROJECT: subweb-new

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2.3.5

      - name: 设置标签
        id: tag
        run: |
          if [[ -n $(cat Dockerfile | awk '{if($1~"ENV" && $2=="VERSION")print $3}') ]]; then
            VERSION=$(cat Dockerfile | awk '{if($1~"ENV" && $2=="VERSION")print $3}')
            echo "tag=$VERSION" >> $GITHUB_ENV
          else
            echo "tag=$(date +%Y)-$(date +%m)-$(date +%d)" >> $GITHUB_ENV
          fi

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v1

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: 登录 Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建并推送到 Docker Hub
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}:${{ env.tag }}

#      - name: 同步 README.md 到 Docker Hub
#        uses: ms-jpq/sync-dockerhub-readme@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}
#          readme: "./README.md"
